### ISSUE TITLE
Docs Feedback - loop of records:updated >> sheet:validated

### ISSUE THREAD

**Issue by jasonhwolf** [FlatFilers/Guides#147]
Not sure if this is expected behavior or not, but using the code examples in the docs brings me into an infinite loop of 
```
sheet:validated
records:updated
sheet:validated
records:updated
sheet:validated
records:updated
...
```

I update one record, and that kicks off the endless line of validations & updates

**Comment by ashleygmulligan2** [comment]
Thank you, can you try again?

**Comment by jasonhwolf** [comment]
does that help @ashleygmulligan2 ?

**Comment by ashleygmulligan2** [comment]
Yes, thank you. This is fixed now.

**Comment by jasonhwolf** [comment]
Not sure if I'm doing something wrong here, but I'm still seeing this happening

**Comment by ashleygmulligan2** [comment]
Just triple checking that you forked the Replit again?

**Comment by ashleygmulligan2** [comment]
This should now be fixed.
