### ISSUE TITLE
Customer has an issue doing `npm install`, getting errors

### ISSUE THREAD

**Issue by Arsik36** [FlatFilers/Guides#423]
Path: /quickstart/deploying

We have a customer Penchecks who is trying to use the new docs to integrate Flatfile. First, they pulled the configuration from this Github repository - https://github.com/FlatFilers/getting-started

Then, when they run `npm install` they are getting the following error, seems like referenced packages are no longer available:

```
npm WARN deprecated @flatfile/orm@0.1.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@flatfile/plugin-transform/-/plugin-transform-0.0.1.tgz - Not found
npm ERR! 404
npm ERR! 404  '@flatfile/plugin-transform@https://registry.npmjs.org/@flatfile/plugin-transform/-/plugin-transform-0.0.1.tgz' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url. 
```

According to Ashley, this is because the getting started project should mirror our [repl.it](http://repl.it/), but it got out of sync.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_9u9n0)

**Comment by ashleygmulligan2** [comment]
This is resolved

**Comment by Arsik36** [comment]
@ashleygmulligan2 `npm update` still throws this for me. Can we update that too as part of that ticket?
<img width="700" alt="Screenshot 2023-05-05 at 8 37 49 AM" src="https://user-images.githubusercontent.com/61366150/236503665-507dfc8e-9901-469c-b08c-50416391fd8f.png">
